### ISSUE TITLE
Peer to peer review Part 2

### ISSUE THREAD

**Issue by algerina** [lu-jim/to-do#2]
Great job so far, since the project is not yet complete I didn't notice issues but I will recommend you to not add the Dist folder to the Gitignore.

**Comment by Medini-Rajendra** [comment]
Great Job Luis!!! The project design is as per the requirements. However, updating Readme File along with the project would be a plus. Other than there is nothing else to commit. Good Luck!!!

**Comment by lu-jim** [comment]
Both done!
